        <!-- We store a copy of the menubar in menubar.inc.  Better to include
             that when you modify it, so the changes get propagated.-->
        <!-- Be sure to modify the "active" item -->

        <div class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="http://yt-project.org/">yt project</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="about.html">About</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Docs<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="http://yt-project.org/docs/dev">Dev</a></li>
                    <li><a href="http://yt-project.org/docs/2.5">2.5</a></li>
                    <li><a href="http://yt-project.org/docs/2.4">2.4</a></li>
                    <li><a href="http://yt-project.org/docs/2.3">2.3</a></li>
                    <li><a href="http://yt-project.org/docs/2.2">2.2</a></li>
                    <li><a href="http://yt-project.org/docs/2.1">2.1</a></li>
                  </ul>
                </li>
                <li><a href="community.html">Community</a></li>
                <li><a href="development.html">Develop</a></li>
                <li><a href="gallery.html">Gallery</a></li>
                <li><a href="https://hub.yt-project.org/">Data Hub</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quick Links <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-header">Learning</li>
                    <li><a href="http://blog.yt-project.org/">yt Blog</a></li>
                    <li><a href="http://yt-project.org/doc/orientation/index.html#orientation">Quick Start</a></li>
                    <li><a href="http://yt-project.org/doc/">Documentation</a></li>
                    <li><a href="http://adsabs.harvard.edu/abs/2011ApJS..192....9T">APJS paper</a>
                    <li class="divider"></li>
                    <li class="dropdown-header">Help!</li>
                    <li><a href="http://lists.spacepope.org/listinfo.cgi/yt-users-spacepope.org">Mailing List</a></li>
                    <li><a href="http://yt-project.org/irc.html">Live Chat</a></li>
                    <li><a href="http://yt-project.org/doc/cheatsheet.pdf">Cheat sheet</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Development</li>
                    <li><a href="http://hg.yt-project.org/yt/issues/new">Report a Bug</a></li>
                    <li><a href="http://bitbucket.org/yt_analysis/yt">Project Page</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <!-- End of menubar.inc inclusion -->
